FROM ubuntu:22.04

ARG LLVM_VERSION=18

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

ENV PATH="/usr/lib/llvm-${LLVM_VERSION}/bin:${PATH}"

WORKDIR /BRiCk
COPY . .

RUN apt-get update \
    && apt-get install -y \
        sudo \
        gnupg \
        locales \
        wget \
        nano \
        fonts-powerline \
        lsb-release \
        software-properties-common \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN locale-gen en_US.UTF-8 
 
RUN apt update \
    && apt install -y \
        build-essential \
        cmake \
        curl \
        cutils \
        git \
        make \
        pkg-config \
        python3 \
        python3-pip \
        neovim \
        bc \
        cpio \
        rsync \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --set python /usr/bin/python3 

RUN cd /opt && wget https://apt.llvm.org/llvm.sh
RUN chmod +x /opt/llvm.sh \
    && /opt/llvm.sh $LLVM_VERSION all \
    && rm /opt/llvm.sh

# TODO: fix clang deps from opam conf-clang package
RUN apt update \
    && apt install -y \
        opam \
        libgmp-dev \
        clang \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

RUN opam init --disable-sandboxing --yes && eval $(opam env)

RUN export "PATH=/usr/lib/llvm-${LLVM_VERSION}/bin:$PATH" \
    && opam repo add --dont-select coq-released "https://coq.inria.fr/opam/released" \
    && opam repo add --dont-select iris-dev "git+https://gitlab.mpi-sws.org/iris/opam.git" \
    && opam switch create --empty --repositories=iris-dev,default,coq-released BRiCk \
    && eval $(opam env) \
    && opam update \
    && opam install --yes \
        dune \
    && eval $(opam env) 

RUN cd /opt \
    && git clone https://github.com/ocaml-ppx/ppxlib.git -b 0.29.1 \
    && opam pin add --yes -n ppxlib.0.29.1 ppxlib \
    && git clone https://github.com/bluerock-io/elpi.git -b br-master \
    && opam pin add --yes -n elpi.dev elpi \
    && git clone https://github.com/bluerock-io/coq-elpi.git -b br-master \
    && opam pin add --yes -n coq-elpi coq-elpi \
    && opam pin add --yes -n rocq-elpi coq-elpi \
    && git clone https://github.com/bluerock-io/stdpp.git -b br-master \
    && opam pin add --yes -n coq-stdpp stdpp \
    && opam pin add --yes -n coq-stdpp-bitvector stdpp \
    && git clone https://github.com/bluerock-io/rocq-stdlib.git -b br-master \
    && opam pin add --yes -n rocq-stdlib rocq-stdlib \
    && opam pin add --yes -n coq-stdlib rocq-stdlib \
    && git clone https://github.com/bluerock-io/Coq-Equations.git -b br-main \
    && opam pin add --yes -n rocq-equations Coq-Equations \
    && git clone https://github.com/bluerock-io/coq.git -b br-master \
    && opam pin add --yes -n rocq-core coq \
    && opam pin add --yes -n rocq-runtime coq \ 
    && opam pin add --yes -n rocq-prover coq \ 
    && opam pin add --yes -n rocq-devtools coq \ 
    && opam pin add --yes -n coq coq \ 
    && opam pin add --yes -n coq-core coq \ 
    && opam pin add --yes -n coqide-server coq \ 
    && git clone https://github.com/bluerock-io/iris.git -b br-master \
    && opam pin add --yes -n coq-iris iris \
    && opam pin add --yes -n coq-iris-heap-lang iris \
    && opam update \
    && eval $(opam env) \
    && opam install --yes --deps-only coq 

 
CMD ["/bin/bash"]
